<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.45">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Explore a data-driven journey into predicting and mitigating customer churn with this project on predictive analytics. Leveraging a Random Forest Classifier, discover insights that empower businesses to proactively retain customers and enhance overall satisfaction.">

<title>Airline On-Time EDA – marcocamilo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">marcocamilo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../portfolio.html"> 
<span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#importing-packages-and-data" id="toc-importing-packages-and-data" class="nav-link active" data-scroll-target="#importing-packages-and-data">Importing Packages and Data</a></li>
  <li><a href="#time-variables" id="toc-time-variables" class="nav-link" data-scroll-target="#time-variables">Time Variables</a>
  <ul>
  <li><a href="#value-counts" id="toc-value-counts" class="nav-link" data-scroll-target="#value-counts">Value Counts</a></li>
  <li><a href="#understanding-0s-2400s-and-nans" id="toc-understanding-0s-2400s-and-nans" class="nav-link" data-scroll-target="#understanding-0s-2400s-and-nans">Understanding 0s, 2400s and NaNs</a></li>
  <li><a href="#feature-engineering-datetime-conversion" id="toc-feature-engineering-datetime-conversion" class="nav-link" data-scroll-target="#feature-engineering-datetime-conversion">Feature Engineering: Datetime Conversion</a></li>
  <li><a href="#data-cleaning-filling-missing-crs-values" id="toc-data-cleaning-filling-missing-crs-values" class="nav-link" data-scroll-target="#data-cleaning-filling-missing-crs-values">Data Cleaning: Filling Missing CRS Values</a></li>
  <li><a href="#data-cleaning-imputing-date-and-time-zones-for-datetime-objects" id="toc-data-cleaning-imputing-date-and-time-zones-for-datetime-objects" class="nav-link" data-scroll-target="#data-cleaning-imputing-date-and-time-zones-for-datetime-objects">Data Cleaning: Imputing Date and Time Zones for Datetime Objects</a></li>
  <li><a href="#feature-engineering-binary-delay-variable" id="toc-feature-engineering-binary-delay-variable" class="nav-link" data-scroll-target="#feature-engineering-binary-delay-variable">Feature Engineering: Binary Delay Variable</a></li>
  <li><a href="#data-cleaning-changing-data-types" id="toc-data-cleaning-changing-data-types" class="nav-link" data-scroll-target="#data-cleaning-changing-data-types">Data Cleaning: Changing Data Types</a></li>
  </ul></li>
  <li><a href="#departure-and-arrival-variables-updated" id="toc-departure-and-arrival-variables-updated" class="nav-link" data-scroll-target="#departure-and-arrival-variables-updated">Departure and Arrival Variables (updated)</a>
  <ul>
  <li><a href="#time-variables-1" id="toc-time-variables-1" class="nav-link" data-scroll-target="#time-variables-1">Time Variables</a></li>
  <li><a href="#delay-variables" id="toc-delay-variables" class="nav-link" data-scroll-target="#delay-variables">Delay Variables</a></li>
  </ul></li>
  <li><a href="#flight-summary-variables" id="toc-flight-summary-variables" class="nav-link" data-scroll-target="#flight-summary-variables">Flight Summary Variables</a>
  <ul>
  <li><a href="#value-counts-1" id="toc-value-counts-1" class="nav-link" data-scroll-target="#value-counts-1">Value Counts</a></li>
  <li><a href="#data-cleaning-changing-data-types-1" id="toc-data-cleaning-changing-data-types-1" class="nav-link" data-scroll-target="#data-cleaning-changing-data-types-1">Data Cleaning: Changing Data Types</a></li>
  <li><a href="#exploring-distance-outliers" id="toc-exploring-distance-outliers" class="nav-link" data-scroll-target="#exploring-distance-outliers">Exploring Distance Outliers</a></li>
  <li><a href="#data-cleaning-negative-time-values" id="toc-data-cleaning-negative-time-values" class="nav-link" data-scroll-target="#data-cleaning-negative-time-values">Data Cleaning: Negative Time Values</a></li>
  <li><a href="#feature-engineering-elapsed-time-calculation" id="toc-feature-engineering-elapsed-time-calculation" class="nav-link" data-scroll-target="#feature-engineering-elapsed-time-calculation">Feature Engineering: Elapsed Time Calculation</a></li>
  <li><a href="#value-counts-updated" id="toc-value-counts-updated" class="nav-link" data-scroll-target="#value-counts-updated">Value Counts (updated)</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul>
  <li><a href="#takeaways" id="toc-takeaways" class="nav-link" data-scroll-target="#takeaways">Takeaways</a></li>
  <li><a href="#exporting-dataset-and-variables" id="toc-exporting-dataset-and-variables" class="nav-link" data-scroll-target="#exporting-dataset-and-variables">Exporting Dataset and Variables</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Airline On-Time EDA</h1>
<p class="subtitle lead">Exploring Airline Performance from 2 Million Flights across 40 Years</p>
</div>

<div>
  <div class="description">
    Explore a data-driven journey into predicting and mitigating customer churn with this project on predictive analytics. Leveraging a Random Forest Classifier, discover insights that empower businesses to proactively retain customers and enhance overall satisfaction.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="https://i.dailymail.co.uk/i/pix/2013/05/02/article-2318173-19957F94000005DC-90_964x639.jpg" class="img-fluid"></p>
<p>Embark on a data-driven exploration into predicting and mitigating customer churn with our project on predictive analytics. By harnessing the power of a Random Forest Classifier, uncover valuable insights that enable businesses to preemptively address customer churn and elevate overall satisfaction. Join us on this journey as we delve into the realm of customer retention and optimization.</p>
<section id="importing-packages-and-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-packages-and-data">Importing Packages and Data</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.gridspec <span class="im">import</span> GridSpec</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> missingno <span class="im">as</span> msno</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="st">"./src/modules/"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> variables_03 <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mac_functions <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>figsize <span class="op">=</span> (<span class="dv">14</span>,<span class="dv">8</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> figsize</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(rc<span class="op">=</span>{<span class="st">'figure.figsize'</span>:figsize})</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.max_columns'</span>, <span class="dv">200</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>pd.options.display.float_format <span class="op">=</span> <span class="st">'</span><span class="sc">{:,.3f}</span><span class="st">'</span>.<span class="bu">format</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_parquet(<span class="st">'./data/interim/03-airline_2m.parquet'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="time-variables" class="level2">
<h2 class="anchored" data-anchor-id="time-variables">Time Variables</h2>
<p>We decide to analyze the time variables (<code>CRSDepTime</code>, <code>DepTime</code>, <code>CRSArrTime</code>, <code>ArrTime</code>) separate from the delay variables, as they require different data cleaning tasks and provide deeper insights into the distribution of the data. We will start by analyzing the distribution of these variables and determine any potential issues that may require further processing.</p>
<section id="value-counts" class="level3">
<h3 class="anchored" data-anchor-id="value-counts">Value Counts</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>time_cols <span class="op">=</span> [<span class="st">'CRSDepTime'</span>, <span class="st">'DepTime'</span>, <span class="st">'CRSArrTime'</span>, <span class="st">'ArrTime'</span>]</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'red'</span>, <span class="st">'green'</span>, <span class="st">'yellow'</span>, <span class="st">'blue'</span>]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>time_hist(df, time_cols, colors, <span class="dv">75</span>, <span class="st">'Distribution of CRS and True Depature and Arrivals'</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>time_hist(df, time_cols, colors, <span class="dv">100</span>, <span class="st">'Distribution of CRS and True Depature and Arrivals: Zoomed into Values 0-100'</span>, limit<span class="op">=</span><span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-3-output-1.png" class="img-fluid"></p>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-3-output-2.png" class="img-fluid"></p>
<p>The histograms above reveal several insights about the nature of time variables in the dataset. Firstly, we see the distribution is not continuous, but discrete with regular gaps throughout the range of values. This is probably due to the HHMM format, which, representing time values, excludes all values between 60 and 99. This results in a discontinous range of values, which is not ideal for out analysis.</p>
<p>Moreover, there is a markedly lower frequency of values below 500, showing that flights before 500 are less frequent. The second histogram zooms into this range. The plot not only demosntrates the progression in the number of <em>red eye</em> flights between midnight and 5am, but also shows more clearly that the distribution of values is regularly discontinuous at values between 60 and 99. This confirms that HHMM is not a suitable format for time operations, and is instead must be replaced by a <code>datetime</code> object. Moreover, late-night <code>ArrTime</code> values in particular seem to be the most frequent among the time variables.</p>
<p>Finally, there is a markedly large number of 0s among time variables. This could suggest that missing values are expressed by means of a 0 value. This might represent a two-fold issue: 0 is representing missing values, while 2400 represents midnight in an invalid time format. This results in midnight values and missing values are undistinguishable in the dataset. This will require some processing before converting values to a <code>datetime</code> object.</p>
<p>We will now address these issues in the following sections.</p>
</section>
<section id="understanding-0s-2400s-and-nans" class="level3">
<h3 class="anchored" data-anchor-id="understanding-0s-2400s-and-nans">Understanding 0s, 2400s and NaNs</h3>
<p>We will start by exploring the value counts of 0s, 2400s and missing values in the time variables. We will then decide how to handle these values.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'0'</span>: df[time_cols].eq(<span class="dv">0</span>).<span class="bu">sum</span>(),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'na'</span>: df[time_cols].isna().<span class="bu">sum</span>(),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'2400'</span>: df[time_cols].eq(<span class="dv">2400</span>).<span class="bu">sum</span>()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>0</th>
<th>na</th>
<th>2400</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CRSDepTime</td>
<td>6464</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>DepTime</td>
<td>0</td>
<td>0</td>
<td>160</td>
</tr>
<tr class="odd">
<td>CRSArrTime</td>
<td>6464</td>
<td>0</td>
<td>37</td>
</tr>
<tr class="even">
<td>ArrTime</td>
<td>0</td>
<td>0</td>
<td>710</td>
</tr>
</tbody>
</table>
<p>The value counts show some interesting patterns. Both CRS variables <code>CRSDepTime</code> and <code>CRSArrTime</code> have the <em>exact</em> same number of 0s and do not contain missing values. This makes it highly likely that these values represent missing values. Additionally, the 2400 values occur mostly in true time variables and tend more to be arrival times. They are likely to represent midnight, but are not supported by the <code>datetime</code> object.</p>
<p>Given the spike of 0 values shown in the histogram above, along with the complete absence of NaN values in the CRS variables, we can conclude that the 0s in the CRS variables represent missing values. We will deal with how to fill these values in a later section.</p>
</section>
<section id="feature-engineering-datetime-conversion" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering-datetime-conversion">Feature Engineering: Datetime Conversion</h3>
<p>As we stated above, the HHMM format is not a suitable format for time operations, and is instead must be replaced by a <code>datetime</code> object. We will start by converting the time variables to a <code>datetime</code> object. This will allow us to perform date operations and visualizations.</p>
<p>However, in order to do this, we must also account for the 0s and 2400s in the CRS variables, as well as the NaN values in the true time variables. We will create a function that will convert the time variables to a <code>datetime</code> object, while also accounting for these values.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> convert_to_datetime(df, time_cols, date):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    matrix <span class="op">=</span> df[time_cols].values</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    matrix <span class="op">=</span> matrix.astype(<span class="st">'int'</span>).astype(<span class="st">'str'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    matrix <span class="op">=</span> np.char.zfill(matrix, <span class="dv">4</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    matrix[matrix <span class="op">==</span> <span class="st">'0000'</span>] <span class="op">=</span> np.nan</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    matrix[matrix <span class="op">==</span> <span class="st">'2400'</span>] <span class="op">=</span> <span class="st">'0000'</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    df[time_cols] <span class="op">=</span> matrix</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> time_cols:</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        df[col] <span class="op">=</span> pd.to_datetime(date <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span> df[col], <span class="bu">format</span><span class="op">=</span><span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st"> %H%M"</span>, errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> convert_to_datetime(df, time_cols, df[<span class="st">'FlightDate'</span>].astype(<span class="bu">str</span>))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>df[time_cols]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="table">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
1998-01-02 16:40:00
</td>
<td>
1998-01-02 16:59:00
</td>
<td>
1998-01-02 18:36:00
</td>
<td>
1998-01-02 18:59:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
2009-05-28 12:04:00
</td>
<td>
2009-05-28 12:02:00
</td>
<td>
2009-05-28 15:41:00
</td>
<td>
2009-05-28 15:41:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
2013-06-29 16:30:00
</td>
<td>
2013-06-29 16:44:00
</td>
<td>
2013-06-29 19:45:00
</td>
<td>
2013-06-29 19:42:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
2010-08-31 13:05:00
</td>
<td>
2010-08-31 13:05:00
</td>
<td>
2010-08-31 20:35:00
</td>
<td>
2010-08-31 20:15:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
2006-01-15 18:20:00
</td>
<td>
2006-01-15 19:11:00
</td>
<td>
2006-01-15 20:26:00
</td>
<td>
2006-01-15 20:58:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
…
</td>
<td>
…
</td>
<td>
…
</td>
<td>
…
</td>
<td>
…
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1958943
</td>
<td>
2008-03-23 14:40:00
</td>
<td>
2008-03-23 14:44:00
</td>
<td>
2008-03-23 15:50:00
</td>
<td>
2008-03-23 15:43:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1958944
</td>
<td>
1999-01-05 09:45:00
</td>
<td>
1999-01-05 09:45:00
</td>
<td>
1999-01-05 12:42:00
</td>
<td>
1999-01-05 12:34:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1958945
</td>
<td>
2003-11-14 12:25:00
</td>
<td>
2003-11-14 12:19:00
</td>
<td>
2003-11-14 13:19:00
</td>
<td>
2003-11-14 13:08:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1958946
</td>
<td>
2012-05-15 18:30:00
</td>
<td>
2012-05-15 18:38:00
</td>
<td>
2012-05-15 19:50:00
</td>
<td>
2012-05-15 19:47:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1958947
</td>
<td>
2003-04-29 16:15:00
</td>
<td>
2003-04-29 16:10:00
</td>
<td>
2003-04-29 17:24:00
</td>
<td>
2003-04-29 17:10:00
</td>
</tr>
</tbody>
</table>
<p>
1958948 rows × 4 columns
</p>
</section></section></main></div>
<p>Now, all values are in a valid <code>datetime</code> format, and in a continuous range of values. Moreover, all 0 values are now uniformely represented by NaN values. Below we print the missing value counts for the CRS variables, to confirm they have the same value count as 0s before this transformation.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df[time_cols].isna().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>CRSDepTime    6464
DepTime          0
CRSArrTime    6464
ArrTime          0
dtype: int64</code></pre>

<section id="data-cleaning-filling-missing-crs-values" class="level3">
<h3 data-anchor-id="data-cleaning-filling-missing-crs-values">Data Cleaning: Filling Missing CRS Values</h3>
<p>We will now consider how to best fill in the missing CRS values. Our first option is to attempt to fill them using information from other variables. We will start by exploring the rows with missing time values to see if there is any pattern that could help us fill them.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df[df[time_cols].isna().<span class="bu">any</span>(axis<span class="op">=</span><span class="dv">1</span>)][dep_cols <span class="op">+</span> arr_cols].sample(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
DepDelay
</th>
<th data-quarto-table-cell-role="th">
DepDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
DepDel15
</th>
<th data-quarto-table-cell-role="th">
DepartureDelayGroups
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrDelay
</th>
<th data-quarto-table-cell-role="th">
ArrDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
ArrDel15
</th>
<th data-quarto-table-cell-role="th">
ArrivalDelayGroups
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
259064
</td>
<td>
NaT
</td>
<td>
1996-01-29 10:01:00
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
NaT
</td>
<td>
1996-01-29 12:54:00
</td>
<td>
-4.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1476653
</td>
<td>
NaT
</td>
<td>
1995-12-04 19:03:00
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
NaT
</td>
<td>
1995-12-04 21:48:00
</td>
<td>
-12.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
292410
</td>
<td>
NaT
</td>
<td>
1999-03-03 22:25:00
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
NaT
</td>
<td>
1999-03-03 00:50:00
</td>
<td>
6.000
</td>
<td>
6.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
450293
</td>
<td>
NaT
</td>
<td>
1996-01-17 08:10:00
</td>
<td>
-1.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
<td>
NaT
</td>
<td>
1996-01-17 11:47:00
</td>
<td>
-4.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1389309
</td>
<td>
NaT
</td>
<td>
1995-11-05 10:09:00
</td>
<td>
8.000
</td>
<td>
8.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
NaT
</td>
<td>
1995-11-05 15:17:00
</td>
<td>
12.000
</td>
<td>
12.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
802408
</td>
<td>
NaT
</td>
<td>
1995-08-08 19:24:00
</td>
<td>
49.000
</td>
<td>
49.000
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
NaT
</td>
<td>
1995-08-08 20:40:00
</td>
<td>
49.000
</td>
<td>
49.000
</td>
<td>
1.000
</td>
<td>
3.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1477057
</td>
<td>
NaT
</td>
<td>
1998-01-13 07:18:00
</td>
<td>
18.000
</td>
<td>
18.000
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
NaT
</td>
<td>
1998-01-13 08:10:00
</td>
<td>
30.000
</td>
<td>
30.000
</td>
<td>
1.000
</td>
<td>
2.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1312808
</td>
<td>
NaT
</td>
<td>
1995-03-02 08:25:00
</td>
<td>
-3.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
<td>
NaT
</td>
<td>
1995-03-02 10:40:00
</td>
<td>
-4.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1536069
</td>
<td>
NaT
</td>
<td>
1998-01-18 21:21:00
</td>
<td>
141.000
</td>
<td>
141.000
</td>
<td>
1.000
</td>
<td>
9.000
</td>
<td>
NaT
</td>
<td>
1998-01-18 23:38:00
</td>
<td>
93.000
</td>
<td>
93.000
</td>
<td>
1.000
</td>
<td>
6.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
866256
</td>
<td>
NaT
</td>
<td>
1999-06-19 15:42:00
</td>
<td>
2.000
</td>
<td>
2.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
NaT
</td>
<td>
1999-06-19 16:58:00
</td>
<td>
-12.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
</tbody>
</table>
</div>
<p>From the rows sample we can see that flights with CRS missing time values all have the rest of their departure and arrival information. Although we can see from the above value counts that delay variables still have a small amount of missing values, we can consider calculating the missing values from the true departure and arrival times, and the delay variables. This will allow us to fill the missing values with the sum of the true time and the delay.</p>
<p>Before we proceed, lets drop the rows with missing delay time values, since their miniscule amount will not affect our analysis.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Before delay drop: </span><span class="sc">{</span>df<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>dep_cols[<span class="dv">1</span>:] <span class="op">+</span> arr_cols[<span class="dv">1</span>:])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"After delay drop: </span><span class="sc">{</span>df<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Before delay drop: (1958948, 43)
After delay drop: (1958862, 43)</code></pre>
<p>Now, we will fill the missing CRS values by using the <code>.fillna()</code> function and use the sum of the true time and the delay as the fill-in value. We will do this for both the <code>DepTime</code> and <code>ArrTime</code> variables, and print the missing value counts for the time variables to confirm the changes.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'CRSDepTime'</span>] <span class="op">=</span> df[<span class="st">'CRSDepTime'</span>].fillna(df[<span class="st">'DepTime'</span>] <span class="op">-</span> pd.to_timedelta(df[<span class="st">'DepDelay'</span>], unit<span class="op">=</span><span class="st">'m'</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'CRSArrTime'</span>] <span class="op">=</span> df[<span class="st">'CRSArrTime'</span>].fillna(df[<span class="st">'ArrTime'</span>] <span class="op">-</span> pd.to_timedelta(df[<span class="st">'ArrDelay'</span>], unit<span class="op">=</span><span class="st">'m'</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>df[time_cols].isna().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>CRSDepTime    0
DepTime       0
CRSArrTime    0
ArrTime       0
dtype: int64</code></pre>
</section>
<section id="data-cleaning-imputing-date-and-time-zones-for-datetime-objects" class="level3">
<h3 data-anchor-id="data-cleaning-imputing-date-and-time-zones-for-datetime-objects">Data Cleaning: Imputing Date and Time Zones for Datetime Objects</h3>
<p>Before moving on, we must address an unfinished issue. Despite the datatype conversion of time variables to <code>datetime</code>, all time variables contain the same date, namely <code>FlightDate</code>. For many cases this is not an issue, however, for flights that span midnight or cross time zones, this could be a problem. Moreover, the times are in local time and do not contain time zone information.</p>
<p>In order to accurately add the flight dates, we will need to add the time zone for all time values in the dataset. We will import a processed dataset with the time zone information for each state or territory, and create a function that maps the departure and arrival times to the corresponding time zone, based on their departure and arrival states. In case of any ambiguous or non-existent times, we will set them to <code>NaT</code> and drop them, if the number of such values is negligible.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>state_tz_df <span class="op">=</span> pd.read_parquet(<span class="st">'data/processed/state_tz.parquet'</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>state_tz_dict <span class="op">=</span> state_tz_df.set_index(<span class="st">'state'</span>)[<span class="st">'tz'</span>].to_dict()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> time_zone(df, time_col, location_col):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    timezones <span class="op">=</span> df[location_col].<span class="bu">map</span>(state_tz_dict)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    times <span class="op">=</span> pd.to_datetime(df[time_col])</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    unique_timezones <span class="op">=</span> timezones.unique()</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> tz <span class="kw">in</span> unique_timezones:</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>        mask <span class="op">=</span> timezones <span class="op">==</span> tz</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>        df.loc[mask, time_col] <span class="op">=</span> times[mask].dt.tz_localize(tz, ambiguous<span class="op">=</span><span class="st">'NaT'</span>, nonexistent<span class="op">=</span><span class="st">'NaT'</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> df[time_col].isna().mean() <span class="op">&lt;</span> <span class="fl">0.01</span>:</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[time_col])</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Check </span><span class="sc">{</span>time_col<span class="sc">}</span><span class="ss"> for NaT"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> time_col <span class="kw">in</span> time_cols[:<span class="dv">2</span>]:</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> time_zone(df, time_col, <span class="st">'OriginState'</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> time_col <span class="kw">in</span> time_cols[<span class="dv">2</span>:]:</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> time_zone(df, time_col, <span class="st">'DestState'</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>display(df[[<span class="st">'OriginState'</span>] <span class="op">+</span> time_cols[:<span class="dv">2</span>] <span class="op">+</span> [<span class="st">'DestState'</span>] <span class="op">+</span> time_cols[<span class="dv">2</span>:]].head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
OriginState
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
DestState
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
MN
</td>
<td>
1998-01-02 16:40:00-06:00
</td>
<td>
1998-01-02 16:59:00-06:00
</td>
<td>
UT
</td>
<td>
1998-01-02 18:36:00-07:00
</td>
<td>
1998-01-02 18:59:00-07:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
WI
</td>
<td>
2009-05-28 12:04:00-05:00
</td>
<td>
2009-05-28 12:02:00-05:00
</td>
<td>
FL
</td>
<td>
2009-05-28 15:41:00-05:00
</td>
<td>
2009-05-28 15:41:00-05:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
CO
</td>
<td>
2013-06-29 16:30:00-06:00
</td>
<td>
2013-06-29 16:44:00-06:00
</td>
<td>
TX
</td>
<td>
2013-06-29 19:45:00-06:00
</td>
<td>
2013-06-29 19:42:00-06:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
CA
</td>
<td>
2010-08-31 13:05:00-07:00
</td>
<td>
2010-08-31 13:05:00-07:00
</td>
<td>
MI
</td>
<td>
2010-08-31 20:35:00-05:00
</td>
<td>
2010-08-31 20:15:00-05:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
NJ
</td>
<td>
2006-01-15 18:20:00-05:00
</td>
<td>
2006-01-15 19:11:00-05:00
</td>
<td>
NC
</td>
<td>
2006-01-15 20:26:00-05:00
</td>
<td>
2006-01-15 20:58:00-05:00
</td>
</tr>
</tbody>
</table>
</div>
<p>Now that all times have their corresponding time zones, we can accurately calculate the dates for all time variables. We assume that the <code>FlightDate</code> only applies to the scheduled flight departure. Consequently, all other time variables will have to be calculated based on the <code>FlightDate</code> and the time difference between the <code>CRSDepTime</code> and the rest of the time variables. To achieve this, we will write a function that takes two columns: the time variable and its corresponding state variable (whether departure or arrival state). The function will convert the time variable to UTC and calculate the time difference between the variable and the <code>CRSDepTime</code>. Then, it will add this difference to the original time variable, which will result in an accurate date in UTC. Finally, the function will search the time zone of the corresponding state and convert the datetime object back to its original time zone.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> date_calculation(df, time_col, location_col, deptime<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    timezones <span class="op">=</span> df[location_col].<span class="bu">map</span>(state_tz_dict)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    times <span class="op">=</span> df[time_col]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    utc_crs_dep <span class="op">=</span> pd.to_datetime(df[<span class="st">'CRSDepTime'</span>], utc<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    utc_times <span class="op">=</span> pd.to_datetime(times, utc<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    diff <span class="op">=</span> (utc_times <span class="op">-</span> utc_crs_dep).dt.seconds</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> deptime:</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>        diff <span class="op">-=</span> (utc_crs_dep.dt.time <span class="op">&gt;</span> utc_times.dt.time) <span class="op">*</span> <span class="dv">86400</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    new_times <span class="op">=</span> utc_crs_dep <span class="op">+</span> pd.to_timedelta(diff, <span class="st">'s'</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    unique_timezones <span class="op">=</span> timezones.unique()</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> tz <span class="kw">in</span> unique_timezones:</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>        mask <span class="op">=</span> timezones <span class="op">==</span> tz</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>        df.loc[mask, time_col] <span class="op">=</span> new_times[mask].dt.tz_convert(tz)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> date_calculation(df, <span class="st">'CRSArrTime'</span>, <span class="st">'DestState'</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> date_calculation(df, <span class="st">'ArrTime'</span>, <span class="st">'DestState'</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> date_calculation(df, <span class="st">'DepTime'</span>, <span class="st">'OriginState'</span>, <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>To make sure that the date calculations are accurate, we will check the dataset for arrival variables that are earlier than their corresponding departure variable.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>negative_crsarr <span class="op">=</span> df.query(<span class="st">"CRSArrTime &lt; CRSDepTime"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>negative_arr <span class="op">=</span> df.query(<span class="st">"ArrTime &lt; DepTime"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"There are </span><span class="sc">{</span>negative_crsarr<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> negative CRSArrTime values: </span><span class="sc">{</span>negative_crsarr<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="op">/</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:.2%}</span><span class="ss">"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>display(negative_crsarr[[<span class="st">'OriginState'</span>] <span class="op">+</span> time_cols[:<span class="dv">2</span>] <span class="op">+</span> [<span class="st">'DestState'</span>] <span class="op">+</span> time_cols[<span class="dv">2</span>:]])</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"There are </span><span class="sc">{</span>negative_arr<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> negative ArrTime values: </span><span class="sc">{</span>negative_arr<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="op">/</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:.2%}</span><span class="ss">"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>display(negative_arr[[<span class="st">'OriginState'</span>] <span class="op">+</span> time_cols[:<span class="dv">2</span>] <span class="op">+</span> [<span class="st">'DestState'</span>] <span class="op">+</span> time_cols[<span class="dv">2</span>:]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>There are 0 negative CRSArrTime values: 0.00%
There are 10307 negative ArrTime values: 0.53%</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
OriginState
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
DestState
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
OriginState
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
DestState
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
259
</td>
<td>
NJ
</td>
<td>
2006-09-10 20:05:00-04:00
</td>
<td>
2006-09-11 19:55:00-04:00
</td>
<td>
GA
</td>
<td>
2006-09-10 22:29:00-04:00
</td>
<td>
2006-09-10 22:27:00-04:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
362
</td>
<td>
MI
</td>
<td>
2004-07-14 21:05:00-05:00
</td>
<td>
2004-07-14 22:00:00-05:00
</td>
<td>
NY
</td>
<td>
2004-07-14 22:05:00-04:00
</td>
<td>
2004-07-14 22:58:00-04:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
370
</td>
<td>
FL
</td>
<td>
2010-06-23 20:24:00-05:00
</td>
<td>
2010-06-23 20:28:00-05:00
</td>
<td>
GA
</td>
<td>
2010-06-23 21:34:00-04:00
</td>
<td>
2010-06-23 21:26:00-04:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
440
</td>
<td>
CA
</td>
<td>
2002-10-28 16:00:00-08:00
</td>
<td>
2002-10-29 15:56:00-08:00
</td>
<td>
NV
</td>
<td>
2002-10-28 17:24:00-08:00
</td>
<td>
2002-10-28 17:09:00-08:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
456
</td>
<td>
IL
</td>
<td>
1996-10-18 19:00:00-05:00
</td>
<td>
1996-10-19 18:57:00-05:00
</td>
<td>
NY
</td>
<td>
1996-10-18 22:00:00-04:00
</td>
<td>
1996-10-18 22:02:00-04:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
…
</td>
<td>
…
</td>
<td>
…
</td>
<td>
…
</td>
<td>
…
</td>
<td>
…
</td>
<td>
…
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1958241
</td>
<td>
CA
</td>
<td>
2006-07-29 17:00:00-07:00
</td>
<td>
2006-07-30 16:59:00-07:00
</td>
<td>
CA
</td>
<td>
2006-07-29 17:48:00-07:00
</td>
<td>
2006-07-29 17:53:00-07:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1958542
</td>
<td>
TX
</td>
<td>
2006-06-27 18:05:00-06:00
</td>
<td>
2006-06-28 17:59:00-06:00
</td>
<td>
TX
</td>
<td>
2006-06-27 19:29:00-06:00
</td>
<td>
2006-06-27 19:44:00-06:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1958593
</td>
<td>
TN
</td>
<td>
2012-07-18 09:45:00-05:00
</td>
<td>
2012-07-18 10:22:00-05:00
</td>
<td>
GA
</td>
<td>
2012-07-19 10:38:00-04:00
</td>
<td>
2012-07-18 11:10:00-04:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1958920
</td>
<td>
VA
</td>
<td>
2014-02-23 19:00:00-05:00
</td>
<td>
2014-02-24 18:55:00-05:00
</td>
<td>
GA
</td>
<td>
2014-02-23 20:59:00-05:00
</td>
<td>
2014-02-23 20:55:00-05:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1958943
</td>
<td>
NV
</td>
<td>
2008-03-23 14:40:00-07:00
</td>
<td>
2008-03-23 14:44:00-07:00
</td>
<td>
AZ
</td>
<td>
2008-03-23 15:50:00-06:00
</td>
<td>
2008-03-23 15:43:00-06:00
</td>
</tr>
</tbody>
</table>
<p>
10307 rows × 6 columns
</p>
</div>
<p><img src="https://www.nationsonline.org/maps/US-timezones-map.jpg" class="img-fluid"></p>
<p>There seem to be a few flights with arrival times earlier than their departure times, even in UTC time. For some cases, it is likely due to the fact that some US states have more than one time zone (as shown in the image below), while our timezone dictionary only accounts for one timezone per state. These are the cases for states such as Michigan, Winsconsin, North and South Dakota, Indiana, Texas, Teneessee, Kentucky, among others, which can be seen in the sample data above. For other cases, it is likely due to the fact that some flights span across midnight in UTC, and our function does not account for this. This can be seen in the sample data above, where <code>DepTime</code> has an additional day compared to <code>CRSDepTime</code>.</p>
<p>Since the number of such values is negligible, we will drop these rows from the dataset.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Before drop of negative arrivals: </span><span class="sc">{</span>df<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(negative_arr.index)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"After drop of negative arrivals: </span><span class="sc">{</span>df<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Before drop of negative arrivals: (1958816, 43)
After drop of negative arrivals: (1948509, 43)</code></pre>
</section>
<section id="feature-engineering-binary-delay-variable" class="level3">
<h3 data-anchor-id="feature-engineering-binary-delay-variable">Feature Engineering: Binary Delay Variable</h3>
<p>We will now create binary delay variables for both departure and arrival delays. This will allow us to analyze the distribution of the delays in the dataset and possibly be useful later on for our prediction model. We will add two new binary columns to our DataFrame, <code>DepDelaryBinary</code> and <code>ArrDelaryBinary</code>, which indicate whether the departure and arrival delays, respectively, are greater than the specified tolerance level (10 minutes in this case). We then update our column lists and display the head of the DataFrame for these selected columns.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>tolerance <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df.insert(<span class="dv">25</span>, <span class="st">"DepDelayBinary"</span>, (df[<span class="st">'DepDelayMinutes'</span>] <span class="op">&gt;</span> tolerance).astype(<span class="st">'int'</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>df.insert(<span class="dv">31</span>, <span class="st">"ArrDelayBinary"</span>, (df[<span class="st">'ArrDelayMinutes'</span>] <span class="op">&gt;</span> tolerance).astype(<span class="st">'int'</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>dep_cols.insert(<span class="dv">4</span>, <span class="st">"DepDelayBinary"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>arr_cols.insert(<span class="dv">4</span>, <span class="st">"ArrDelayBinary"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>df[dep_cols <span class="op">+</span> arr_cols].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
DepDelay
</th>
<th data-quarto-table-cell-role="th">
DepDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
DepDelayBinary
</th>
<th data-quarto-table-cell-role="th">
DepDel15
</th>
<th data-quarto-table-cell-role="th">
DepartureDelayGroups
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrDelay
</th>
<th data-quarto-table-cell-role="th">
ArrDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
ArrDelayBinary
</th>
<th data-quarto-table-cell-role="th">
ArrDel15
</th>
<th data-quarto-table-cell-role="th">
ArrivalDelayGroups
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
1998-01-02 16:40:00-06:00
</td>
<td>
1998-01-02 16:59:00-06:00
</td>
<td>
19.000
</td>
<td>
19.000
</td>
<td>
1
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
1998-01-02 18:36:00-07:00
</td>
<td>
1998-01-02 18:59:00-07:00
</td>
<td>
23.000
</td>
<td>
23.000
</td>
<td>
1
</td>
<td>
1.000
</td>
<td>
1.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
2009-05-28 12:04:00-05:00
</td>
<td>
2009-05-28 12:02:00-05:00
</td>
<td>
-2.000
</td>
<td>
0.000
</td>
<td>
0
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
<td>
2009-05-28 15:41:00-05:00
</td>
<td>
2009-05-28 15:41:00-05:00
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0
</td>
<td>
0.000
</td>
<td>
0.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
2013-06-29 16:30:00-06:00
</td>
<td>
2013-06-29 16:44:00-06:00
</td>
<td>
14.000
</td>
<td>
14.000
</td>
<td>
0
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
2013-06-29 19:45:00-06:00
</td>
<td>
2013-06-29 19:42:00-06:00
</td>
<td>
-3.000
</td>
<td>
0.000
</td>
<td>
0
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
2010-08-31 13:05:00-07:00
</td>
<td>
2010-08-31 13:05:00-07:00
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
2010-08-31 20:35:00-05:00
</td>
<td>
2010-08-31 20:15:00-05:00
</td>
<td>
-20.000
</td>
<td>
0.000
</td>
<td>
0
</td>
<td>
0.000
</td>
<td>
-2.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
2006-01-15 18:20:00-05:00
</td>
<td>
2006-01-14 19:11:00-05:00
</td>
<td>
51.000
</td>
<td>
51.000
</td>
<td>
1
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
2006-01-15 20:26:00-05:00
</td>
<td>
2006-01-15 20:58:00-05:00
</td>
<td>
32.000
</td>
<td>
32.000
</td>
<td>
1
</td>
<td>
1.000
</td>
<td>
2.000
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="data-cleaning-changing-data-types" class="level3">
<h3 data-anchor-id="data-cleaning-changing-data-types">Data Cleaning: Changing Data Types</h3>
<p>A minor detail we mentioned above is that the numerical variables measuring duration and boolean variables would benefit from being saved as integers. We will thus convert the delay variables to integers and boolean variables.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df[dep_cols[<span class="dv">2</span>:] <span class="op">+</span> arr_cols[<span class="dv">2</span>:]] <span class="op">=</span> df[dep_cols[<span class="dv">2</span>:] <span class="op">+</span> arr_cols[<span class="dv">2</span>:]].astype(<span class="st">'int'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df[dep_cols[<span class="dv">2</span>:] <span class="op">+</span> arr_cols[<span class="dv">2</span>:]].sample(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
DepDelay
</th>
<th data-quarto-table-cell-role="th">
DepDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
DepDelayBinary
</th>
<th data-quarto-table-cell-role="th">
DepDel15
</th>
<th data-quarto-table-cell-role="th">
DepartureDelayGroups
</th>
<th data-quarto-table-cell-role="th">
ArrDelay
</th>
<th data-quarto-table-cell-role="th">
ArrDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
ArrDelayBinary
</th>
<th data-quarto-table-cell-role="th">
ArrDel15
</th>
<th data-quarto-table-cell-role="th">
ArrivalDelayGroups
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
663927
</td>
<td>
6
</td>
<td>
6
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
23
</td>
<td>
23
</td>
<td>
1
</td>
<td>
1
</td>
<td>
1
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
301250
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
3
</td>
<td>
3
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
573000
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1922332
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-7
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-1
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
335044
</td>
<td>
74
</td>
<td>
74
</td>
<td>
1
</td>
<td>
1
</td>
<td>
4
</td>
<td>
64
</td>
<td>
64
</td>
<td>
1
</td>
<td>
1
</td>
<td>
4
</td>
</tr>
</tbody>
</table>
</div>
</section>

<section id="departure-and-arrival-variables-updated" class="level2">
<h2 data-anchor-id="departure-and-arrival-variables-updated">Departure and Arrival Variables (updated)</h2>
<p>So far, we have explore missing value correlations among departure and arrival variables, dropped unnecessary variables, converted the time variables to <code>datetime</code> format, filled missing CRS values, and created binary delay variables. As mentioned at the start of this section, considering the need for data cleaning and the varying nature of missing values, we can now analyze the distribution of the departure and arrival variables in the dataset.</p>
<p>We will divide our analysis into two parts: the time variables and the delay variables. Given our data has been cleaned, we can finally focus on the statistical analysis of these variables.</p>
<section id="time-variables-1" class="level3">
<h3 data-anchor-id="time-variables-1">Time Variables</h3>
<p>Since our time data is now clean and in a valid format, we will start by analyzing the distribution of the time variables in the dataset. We will use the <code>time_hist</code> function to create a histogram for the time variables.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col, color <span class="kw">in</span> <span class="bu">zip</span>(time_cols, colors):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    times <span class="op">=</span> df[col].<span class="bu">apply</span>(<span class="kw">lambda</span> x : x.time())</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    times <span class="op">=</span> [t.hour <span class="op">*</span> <span class="dv">60</span> <span class="op">+</span> t.minute <span class="cf">for</span> t <span class="kw">in</span> times]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    plt.hist(times, alpha<span class="op">=</span><span class="fl">0.5</span>, bins<span class="op">=</span><span class="dv">75</span>, color<span class="op">=</span>color)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    plt.axvline(np.mean(times), color<span class="op">=</span>color, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>plt.legend(time_cols)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of CRS and True Depature and Arrivals'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>plt.xticks(np.arange(<span class="dv">0</span>, <span class="dv">1441</span>, <span class="dv">60</span>), [<span class="ss">f'</span><span class="sc">{</span>h<span class="sc">}</span><span class="ss">:00'</span> <span class="cf">for</span> h <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">25</span>)])</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
<p>The histogram now shows a clear picture on the distribution of time variables. At first glance, the plot shows departures are more prevalent during morning hours, while arrivals are more predominant during the evening, which is expected. This is further demonstrated by the 2-hour difference in the depature and arrival means, which shows that departures tend to occur earlier on average than arrivals.</p>
<p>Particularly noticeable is the progression of flight frequencies across the day. The data shows that early morning flights, particularly at 3am, are the least frequent for both depatures and arrivals. However, there is a significant increase in the number of flights at 5am for departures and 7am for arrivals. There is a noticeable of departure flights at 7am, with over 55000 flights registered across the dataset. Afterwards, overall peak hours, where <em>both</em> arrivals and departures are at their highest, remain relatively consistent from 9pm. The number of departures decreases first at 6pm, whereas the number of arrivals starts decreasing from 9pm. This decrease continues past midnight, reaching its lowest point at around 3am.</p>
<p>Moreover, the distribution of CRS and true time variable pairs for departures and arrivals, respectively, are almost identical, as shown by the close pairs of means. This already reveals that the size of flight delays is small on average across the dataset.</p>
<p>Given this insight, let us now focus on the distribution of delay variables in particular.</p>
</section>
<section id="delay-variables" class="level3">
<h3 data-anchor-id="delay-variables">Delay Variables</h3>
<div class="sourceCode" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>univariate_preview(df, dep_cols[<span class="dv">2</span>:] <span class="op">+</span> arr_cols[<span class="dv">2</span>:])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>'Data Preview'</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
DepDelay
</th>
<th data-quarto-table-cell-role="th">
DepDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
DepDelayBinary
</th>
<th data-quarto-table-cell-role="th">
DepDel15
</th>
<th data-quarto-table-cell-role="th">
DepartureDelayGroups
</th>
<th data-quarto-table-cell-role="th">
ArrDelay
</th>
<th data-quarto-table-cell-role="th">
ArrDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
ArrDelayBinary
</th>
<th data-quarto-table-cell-role="th">
ArrDel15
</th>
<th data-quarto-table-cell-role="th">
ArrivalDelayGroups
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
19
</td>
<td>
19
</td>
<td>
1
</td>
<td>
1
</td>
<td>
1
</td>
<td>
23
</td>
<td>
23
</td>
<td>
1
</td>
<td>
1
</td>
<td>
1
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
-2
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
14
</td>
<td>
14
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-3
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-1
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-20
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
-2
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
51
</td>
<td>
51
</td>
<td>
1
</td>
<td>
1
</td>
<td>
3
</td>
<td>
32
</td>
<td>
32
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
</tr>
</tbody>
</table>
</div>
<pre><code>'Value Counts'</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
columns
</th>
<th data-quarto-table-cell-role="th">
dtypes
</th>
<th data-quarto-table-cell-role="th">
nunique
</th>
<th data-quarto-table-cell-role="th">
top5
</th>
<th data-quarto-table-cell-role="th">
na%
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
5
</td>
<td>
ArrDelay
</td>
<td>
int64
</td>
<td>
937
</td>
<td>
[0, -5, -3, -2, -4]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
DepDelay
</td>
<td>
int64
</td>
<td>
911
</td>
<td>
[0, -2, -1, -3, -4]
</td>
<td>
0.00%
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
DepDelayMinutes
</td>
<td>
int64
</td>
<td>
855
</td>
<td>
[0, 1, 2, 3, 5]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
6
</td>
<td>
ArrDelayMinutes
</td>
<td>
int64
</td>
<td>
850
</td>
<td>
[0, 2, 1, 3, 5]
</td>
<td>
0.00%
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
DepartureDelayGroups
</td>
<td>
int64
</td>
<td>
15
</td>
<td>
[-1, 0, 1, 2, 3]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
9
</td>
<td>
ArrivalDelayGroups
</td>
<td>
int64
</td>
<td>
15
</td>
<td>
[-1, 0, -2, 1, 2]
</td>
<td>
0.00%
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
DepDelayBinary
</td>
<td>
int64
</td>
<td>
2
</td>
<td>
[0, 1]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
DepDel15
</td>
<td>
int64
</td>
<td>
2
</td>
<td>
[0, 1]
</td>
<td>
0.00%
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
7
</td>
<td>
ArrDelayBinary
</td>
<td>
int64
</td>
<td>
2
</td>
<td>
[0, 1]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
8
</td>
<td>
ArrDel15
</td>
<td>
int64
</td>
<td>
2
</td>
<td>
[0, 1]
</td>
<td>
0.00%
</td>
</tr>
</tbody>
</table>
</div>
<pre><code>'Summary Stats'</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
DepDelay
</th>
<th data-quarto-table-cell-role="th">
DepDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
DepDelayBinary
</th>
<th data-quarto-table-cell-role="th">
DepDel15
</th>
<th data-quarto-table-cell-role="th">
DepartureDelayGroups
</th>
<th data-quarto-table-cell-role="th">
ArrDelay
</th>
<th data-quarto-table-cell-role="th">
ArrDelayMinutes
</th>
<th data-quarto-table-cell-role="th">
ArrDelayBinary
</th>
<th data-quarto-table-cell-role="th">
ArrDel15
</th>
<th data-quarto-table-cell-role="th">
ArrivalDelayGroups
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
count
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
mean
</td>
<td>
8.495
</td>
<td>
10.400
</td>
<td>
0.160
</td>
<td>
0.169
</td>
<td>
0.062
</td>
<td>
6.197
</td>
<td>
11.785
</td>
<td>
0.189
</td>
<td>
0.198
</td>
<td>
-0.074
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
std
</td>
<td>
32.249
</td>
<td>
31.485
</td>
<td>
0.367
</td>
<td>
0.374
</td>
<td>
1.816
</td>
<td>
34.810
</td>
<td>
31.948
</td>
<td>
0.391
</td>
<td>
0.398
</td>
<td>
1.995
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
min
</td>
<td>
-990.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-2.000
</td>
<td>
-706.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-2.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
25%
</td>
<td>
-3.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
<td>
-10.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
50%
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
-1.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
75%
</td>
<td>
6.000
</td>
<td>
6.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
10.000
</td>
<td>
10.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
<td>
0.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
max
</td>
<td>
1,878.000
</td>
<td>
1,878.000
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
12.000
</td>
<td>
1,898.000
</td>
<td>
1,898.000
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
12.000
</td>
</tr>
</tbody>
</table>
</div>
<p>The value counts above show several insights about the delay variables. <code>DepDelay</code> and <code>ArrDelay</code> have the highest number of unique values, since they are continuous variables that include negative values (representing flights ahead of schedule). Interestingly, their top 5 values counts show that on-time and ahead of scheduled flights (by less than 5 minutes) are the most frequent. The delay minutes variables have a lower value count, since they only include positive values. According to the value counts, delays of less than 5 minutes are the most common for both departures and arrivals. The delay groups variables give a deeper glimpse into the amount of delays, as they count the number of 15-minute intervals for flight delays. The most frequent delay groups range from -15 to 30 minutes. The binary delay variables further confirm that the majority of flights are on time.</p>
<p>The summary statistics on the other hand show some concerning facts about the <code>DepDelay</code> and <code>ArrDelay</code> variables in particular. According to the summary statistics, the minimum delay is -990 minutes (or -16.5 hours) for departures and -706 minutes (or -11.8 hours) for arrivals. Conversely, the maximum delay for these, as well as for the delay minutes variables, is 1878 minutes or (31.3 hours) for departures and 1898 minutes (or 31.64 hours) for arrivals. This is highly concerning, as it is unlikely for flights to be delayed by such a large amount of time. This clearly indicates the presence of outliers in the dataset.</p>
<p>Before exploring this issue, let us first visualize the distribution of the categorical variables in this group to better understand what is really happening with flight delays in the dataset. We will start by creating histograms for the delay variables.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>variables <span class="op">=</span> dep_cols[<span class="dv">4</span>:] <span class="op">+</span> arr_cols[<span class="dv">4</span>:]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ncols <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>nvars <span class="op">=</span> <span class="bu">len</span>(variables)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="bu">int</span>(nvars<span class="op">/</span>ncols), ncols<span class="op">=</span>ncols, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">10</span>))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col, ax <span class="kw">in</span> <span class="bu">zip</span>(dep_cols[<span class="dv">4</span>:] <span class="op">+</span> arr_cols[<span class="dv">4</span>:], axes.flatten()):</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> df[col].nunique() <span class="op">&gt;</span> <span class="dv">2</span>:</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>        ax.hist(df[col], bins<span class="op">=</span><span class="dv">30</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>        ax.set_title(col)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>        sns.countplot(x<span class="op">=</span>col, data<span class="op">=</span>df, ax<span class="op">=</span>ax, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>        ax.set_xlabel(<span class="va">None</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>        ax.set_title(col)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
<p>The count plots for categorical delay variables give a better understanding as to why the delay variables have such large outliers. The delay binary variables show that around 80% of flights are on time, with only around 20% exhibiting some kind of delay. Morevoer, the 15-minute delay variables have a similar distribution, indicating that the majority of delayed flights are delayed by 15 minutes or more. This amount is considered as the threshold for a delayed flight by the airline industry.</p>
<p>The histograms for 15-minute delay groups offer a more detailed view of the distribution of delays, as shown with normalized counts below. Firstly, the distribution is right skewed, with more than 40% of flights ahead of schedule by less than 15 minutes and around 30% of flights on time. These two groups together represent around 70% of flights in the dataset. This is consistent with the value counts above, which show that the majority of flights exhibit no delays greater than 15 minutes (represented in these histograms by values less than or equal to 0).</p>
<p>Beyond these values, we can better observe the outliers in the dataset. The distribution has a long, right tail, with an increasingly smaller number of flights experiencing delays greater than 15 minutes. A uniformly low count of flights can be seen for delays greater than three 15-minute intervals (or 45 minutes). These are the flights that are causing the large outliers in the delay variables. Finally, it is worth noting that the <code>ArrivalDelayGroups</code> variable even shows a significant amount of flights (around 13%) arriving ahead of schedule by more than 15 minutes.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">10</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">'DepartureDelayGroups'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>], stat<span class="op">=</span><span class="st">"percent"</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">'ArrivalDelayGroups'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>], stat<span class="op">=</span><span class="st">"percent"</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
<p>We will leave the outlier exploration for these variables, as well as any other, for our next notebook covering the bivariate analysis of this dataset. For now, we will move on to the last sections, to analyze the distribution of the remaining variables in the dataset.</p>
</section>
</section>
<section id="flight-summary-variables" class="level2">
<h2 data-anchor-id="flight-summary-variables">Flight Summary Variables</h2>
<p>We will now analyze the distribution of the flight summary variables, which include <code>FlightDate</code>, <code>UniqueCarrier</code>, <code>FlightNum</code>, <code>TailNum</code>, <code>Distance</code>, <code>DistanceGroup</code>, and <code>DivAirportLandings</code>. We will start by analyzing the distribution of these variables and determine any potential issues that may require further processing.</p>
<section id="value-counts-1" class="level3">
<h3 data-anchor-id="value-counts-1">Value Counts</h3>
<div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>univariate_preview(df, sum_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>'Data Preview'</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
CRSElapsedTime
</th>
<th data-quarto-table-cell-role="th">
ActualElapsedTime
</th>
<th data-quarto-table-cell-role="th">
AirTime
</th>
<th data-quarto-table-cell-role="th">
Distance
</th>
<th data-quarto-table-cell-role="th">
DistanceGroup
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
176.000
</td>
<td>
180.000
</td>
<td>
153.000
</td>
<td>
991.000
</td>
<td>
4
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
157.000
</td>
<td>
159.000
</td>
<td>
141.000
</td>
<td>
1,066.000
</td>
<td>
5
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
135.000
</td>
<td>
118.000
</td>
<td>
103.000
</td>
<td>
773.000
</td>
<td>
4
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
270.000
</td>
<td>
250.000
</td>
<td>
220.000
</td>
<td>
1,979.000
</td>
<td>
8
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
126.000
</td>
<td>
107.000
</td>
<td>
80.000
</td>
<td>
529.000
</td>
<td>
3
</td>
</tr>
</tbody>
</table>
</div>
<pre><code>'Value Counts'</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
columns
</th>
<th data-quarto-table-cell-role="th">
dtypes
</th>
<th data-quarto-table-cell-role="th">
nunique
</th>
<th data-quarto-table-cell-role="th">
top5
</th>
<th data-quarto-table-cell-role="th">
na%
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
Distance
</td>
<td>
float64
</td>
<td>
1902
</td>
<td>
[337.0, 370.0, 236.0, 328.0, 224.0]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
AirTime
</td>
<td>
float64
</td>
<td>
666
</td>
<td>
[50.0, 45.0, 55.0, 60.0, 53.0]
</td>
<td>
19.32%
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
ActualElapsedTime
</td>
<td>
float64
</td>
<td>
664
</td>
<td>
[70.0, 65.0, 75.0, 60.0, 80.0]
</td>
<td>
0.00%
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
CRSElapsedTime
</td>
<td>
float64
</td>
<td>
630
</td>
<td>
[70.0, 65.0, 75.0, 80.0, 60.0]
</td>
<td>
0.00%
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
DistanceGroup
</td>
<td>
int64
</td>
<td>
11
</td>
<td>
[2, 3, 1, 4, 5]
</td>
<td>
0.00%
</td>
</tr>
</tbody>
</table>
</div>
<pre><code>'Summary Stats'</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
CRSElapsedTime
</th>
<th data-quarto-table-cell-role="th">
ActualElapsedTime
</th>
<th data-quarto-table-cell-role="th">
AirTime
</th>
<th data-quarto-table-cell-role="th">
Distance
</th>
<th data-quarto-table-cell-role="th">
DistanceGroup
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
count
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
<td>
1,572,116.000
</td>
<td>
1,948,509.000
</td>
<td>
1,948,509.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
mean
</td>
<td>
127.445
</td>
<td>
125.167
</td>
<td>
106.121
</td>
<td>
736.464
</td>
<td>
3.421
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
std
</td>
<td>
70.524
</td>
<td>
70.390
</td>
<td>
68.602
</td>
<td>
569.531
</td>
<td>
2.246
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
min
</td>
<td>
0.000
</td>
<td>
3.000
</td>
<td>
-703.000
</td>
<td>
11.000
</td>
<td>
1.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
25%
</td>
<td>
75.000
</td>
<td>
74.000
</td>
<td>
56.000
</td>
<td>
325.000
</td>
<td>
2.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
50%
</td>
<td>
109.000
</td>
<td>
107.000
</td>
<td>
87.000
</td>
<td>
583.000
</td>
<td>
3.000
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
75%
</td>
<td>
159.000
</td>
<td>
156.000
</td>
<td>
136.000
</td>
<td>
972.000
</td>
<td>
4.000
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
max
</td>
<td>
705.000
</td>
<td>
975.000
</td>
<td>
965.000
</td>
<td>
5,095.000
</td>
<td>
11.000
</td>
</tr>
</tbody>
</table>
</div>
<p>The value counts shows us that most variables except for <code>DistanceGroup</code> are numerical variables, thus exhibiting a high number of unique values. The values are mostly saved as floats, which, as with the departure and arrival variables in previous sections, might be best to save as integers. Regarding top values, we see that the most frequent values for the <code>Distance</code> column range from the low 200s to the high 300s, <code>AirTime</code> values cluster around 50 minutes, and <code>CRSElapsedTime</code> and <code>ActualElapsedTime</code> at 60 minutes. The <code>DistanceGroup</code> variable is a categorical variable that counts the flight distance in 250-mile intervals. All top values are less than 5, indicating that top flights are less than 1250 miles long.</p>
<p>The summary statistics show a more detailed understanding of the numerical distribution of the variables, which we visualize below.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">3</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">10</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>(ax1, ax2, ax3, ax4, ax5, ax6) <span class="op">=</span> axes.flatten()</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">'Distance'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>ax1, kde<span class="op">=</span><span class="va">True</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>sns.countplot(x<span class="op">=</span><span class="st">'DistanceGroup'</span>, data<span class="op">=</span>df, ax<span class="op">=</span>ax2, edgecolor<span class="op">=</span><span class="st">'black'</span>, stat<span class="op">=</span><span class="st">'percent'</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">'CRSElapsedTime'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>ax3, kde<span class="op">=</span><span class="va">True</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">'ActualElapsedTime'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>ax4, kde<span class="op">=</span><span class="va">True</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>sns.histplot(df[<span class="st">'AirTime'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>ax5, kde<span class="op">=</span><span class="va">True</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-21-output-1.png" class="img-fluid"></p>
<p>Starting with the <code>Distance</code> variable, the histogram shows the distribution is right skewed, with the majority of flights being less than 1000 miles long. The normalized count plot for <code>DistanceGroup</code>, which groups flights into distance groups 250 Miles, shows a similar distribution. According to the summary statistics for these variables, the mean distance for flights in the dataset is 735 miles, with a standard deviation of 569 miles, and 75% of flights being less than 969 miles long or within the first 4 distance group. Fewer flights are longer, which may be the case for flights to Hawaii, Alaska, as well as to U.S. territories and possessions and cross-country flights.</p>
<p>The summary statistics and histograms for <code>CRSElapsedTime</code>, <code>ActualElapsedTime</code>, and <code>AirTime</code> show a different story. The distribution for these variables is also right skewed, with 75% of flights lasting under 160 minutes or 2 hours and 40 minutes from departure to arrival. However, the <code>ActualElapsedTime</code> and, in particular, <code>AirTime</code> variables exhibit negative values, which is not possible for flight times. Two possible explanations for this is that time zone differences, as well as flights spanning across midnight, might have caused the arrival time to be earlier than the departure time. This will require further exploration to confirm, but, if true, would simple require time zone adjustments and simple matrix operations to fix. Finally, the <code>AirTime</code> variable has a large amount of missing values, which will require further processing.</p>
<p>We will explore these issues in the following sections, starting with the question of outlying values in the distance variables. Then we will move on to the issue of negative values in the time variables. But first, we will convert the numerical variables to integers.</p>
</section>
<section id="data-cleaning-changing-data-types-1" class="level3">
<h3 data-anchor-id="data-cleaning-changing-data-types-1">Data Cleaning: Changing Data Types</h3>
<p>We will convert the numerical variables to integers, as they are all counts or durations, and thus do not require decimal points. To allow while keeping the missing values, we will convert the variables to <code>Int64</code> type and ignore missing values using the <code>errors='coerce'</code> argument from <code>pd.to_numeric</code>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df[sum_cols[:<span class="op">-</span><span class="dv">1</span>]] <span class="op">=</span> df[sum_cols[:<span class="op">-</span><span class="dv">1</span>]].<span class="bu">apply</span>(pd.to_numeric, errors<span class="op">=</span><span class="st">'coerce'</span>).astype(<span class="st">'Int64'</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>display(df[sum_cols].dtypes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>CRSElapsedTime       Int64
ActualElapsedTime    Int64
AirTime              Int64
Distance             Int64
DistanceGroup        int64
dtype: object</code></pre>
</section>
<section id="exploring-distance-outliers" class="level3">
<h3 data-anchor-id="exploring-distance-outliers">Exploring Distance Outliers</h3>
<p>We will start by exploring flights with outlying distances. To achieve this, we will filter the dataset for flights with distances greater than the 3rd quartile and preview the unique <code>Origin</code> and <code>Dest</code> value combinations for these flights.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>long_flights <span class="op">=</span> df.query(<span class="st">"Distance &gt; 969"</span>).sort_values(by<span class="op">=</span><span class="st">'Distance'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of flights greater than 3Q (969): </span><span class="sc">{</span>long_flights<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> or </span><span class="sc">{</span>long_flights<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="op">/</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:.2%}</span><span class="ss">"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>display(df.groupby([<span class="st">'Origin'</span>, <span class="st">'Dest'</span>])[<span class="st">'Distance'</span>].<span class="bu">max</span>().reset_index().sort_values(by<span class="op">=</span><span class="st">'Distance'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Number of flights greater than 3Q (969): 488141 or 25.05%</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
Origin
</th>
<th data-quarto-table-cell-role="th">
Dest
</th>
<th data-quarto-table-cell-role="th">
Distance
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
3415
</td>
<td>
HNL
</td>
<td>
BOS
</td>
<td>
5095
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
934
</td>
<td>
BOS
</td>
<td>
HNL
</td>
<td>
5095
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
3426
</td>
<td>
HNL
</td>
<td>
JFK
</td>
<td>
4983
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
4144
</td>
<td>
JFK
</td>
<td>
HNL
</td>
<td>
4983
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2854
</td>
<td>
EWR
</td>
<td>
HNL
</td>
<td>
4963
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3421
</td>
<td>
HNL
</td>
<td>
EWR
</td>
<td>
4963
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
3423
</td>
<td>
HNL
</td>
<td>
IAD
</td>
<td>
4817
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3620
</td>
<td>
IAD
</td>
<td>
HNL
</td>
<td>
4817
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
3416
</td>
<td>
HNL
</td>
<td>
CLT
</td>
<td>
4678
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1528
</td>
<td>
CLT
</td>
<td>
HNL
</td>
<td>
4678
</td>
</tr>
</tbody>
</table>
</div>
<p>As suspected, long distances are mostly flights to or from Hawaii. The aggregation above shows that the top 10 longest flights are all to or from Hawaii, with the longest flight being between Honolulu (HNL) and Boston (BOS). According to the histograms from the previous section, these flights are not only outliers, but are also among the least frequent in the dataset.</p>
<p>Below we show which are the top 10 most frequent flights not involving Hawaii.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>long_flights_not_hawaii <span class="op">=</span> long_flights.query(<span class="st">"~OriginStateName.str.contains('Hawaii') &amp; ~DestStateName.str.contains('Hawaii')"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>display(long_flights_not_hawaii.groupby([<span class="st">'Origin'</span>, <span class="st">'Dest'</span>])[<span class="st">'Distance'</span>].<span class="bu">max</span>().drop_duplicates().reset_index().sort_values(by<span class="op">=</span><span class="st">'Distance'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
Origin
</th>
<th data-quarto-table-cell-role="th">
Dest
</th>
<th data-quarto-table-cell-role="th">
Distance
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
33
</td>
<td>
ANC
</td>
<td>
ATL
</td>
<td>
3417
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
638
</td>
<td>
LAX
</td>
<td>
SJU
</td>
<td>
3386
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
756
</td>
<td>
PHL
</td>
<td>
ANC
</td>
<td>
3379
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
38
</td>
<td>
ANC
</td>
<td>
EWR
</td>
<td>
3370
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
39
</td>
<td>
ANC
</td>
<td>
IAH
</td>
<td>
3266
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
331
</td>
<td>
CVG
</td>
<td>
ANC
</td>
<td>
3110
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
36
</td>
<td>
ANC
</td>
<td>
DFW
</td>
<td>
3043
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
37
</td>
<td>
ANC
</td>
<td>
DTW
</td>
<td>
2986
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
50
</td>
<td>
ANC
</td>
<td>
STL
</td>
<td>
2936
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
44
</td>
<td>
ANC
</td>
<td>
ORD
</td>
<td>
2846
</td>
</tr>
</tbody>
</table>
</div>
<p>As we can see, the longest flights not involving Hawaii are mostly flights betwen Alaska (ANC) and east cost cities like Atlanta (ATL), Philadelphia (PHL), Newark (EWR) and Chicago (IAH). Interestingly, the second longest flight in this groups does not involve either Hawaii or Alaska, but a U.S. territory. This is a flight between San Juan (SJU) and Los Angeles (LAX).</p>
<p>Lastly, we leave below the top 10 longest flights not involving Hawaii or Alaska, which, as expected, mostly involve transcontinental flights.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>long_flights_not_hawaii_alaska <span class="op">=</span> long_flights.query(<span class="st">"~OriginStateName.isin(['Hawaii', 'Alaska']) &amp; ~DestStateName.isin(['Hawaii', 'Alaska'])"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>display(long_flights_not_hawaii_alaska.groupby([<span class="st">'Origin'</span>, <span class="st">'Dest'</span>])[<span class="st">'Distance'</span>].<span class="bu">max</span>().drop_duplicates().reset_index().sort_values(by<span class="op">=</span><span class="st">'Distance'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
Origin
</th>
<th data-quarto-table-cell-role="th">
Dest
</th>
<th data-quarto-table-cell-role="th">
Distance
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
618
</td>
<td>
LAX
</td>
<td>
SJU
</td>
<td>
3386
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
667
</td>
<td>
MIA
</td>
<td>
SEA
</td>
<td>
2724
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
481
</td>
<td>
FLL
</td>
<td>
SEA
</td>
<td>
2717
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
199
</td>
<td>
BOS
</td>
<td>
SFO
</td>
<td>
2704
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
191
</td>
<td>
BOS
</td>
<td>
OAK
</td>
<td>
2694
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
200
</td>
<td>
BOS
</td>
<td>
SJC
</td>
<td>
2689
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
203
</td>
<td>
BOS
</td>
<td>
SMF
</td>
<td>
2636
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
138
</td>
<td>
BDL
</td>
<td>
SFO
</td>
<td>
2625
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
184
</td>
<td>
BOS
</td>
<td>
LAX
</td>
<td>
2611
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
185
</td>
<td>
BOS
</td>
<td>
LGB
</td>
<td>
2602
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="data-cleaning-negative-time-values" class="level3">
<h3 data-anchor-id="data-cleaning-negative-time-values">Data Cleaning: Negative Time Values</h3>
<p>In this section, we will explore the issue of negative time values in the <code>ActualElapsedTime</code> and <code>AirTime</code> variables. We will start by filtering the dataset for flights with negative <code>ActualElapsedTime</code> and <code>AirTime</code> values and preview the departure and arrival times (both CRS and real) for these flights, along with their origin and destination states to account for time differences.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>negative_times <span class="op">=</span> df.query(<span class="st">"ActualElapsedTime &lt; 0 | AirTime &lt; 0"</span>)[[<span class="st">'OriginState'</span>, <span class="st">'DestState'</span>, <span class="st">'CRSDepTime'</span>, <span class="st">'CRSArrTime'</span>, <span class="st">'DepTime'</span>, <span class="st">'ArrTime'</span>, <span class="st">'ActualElapsedTime'</span>, <span class="st">'AirTime'</span>]]</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of negative values in `ActualElapsedTime`: </span><span class="sc">{</span>negative_times<span class="sc">.</span>query(<span class="st">'ActualElapsedTime &lt; 0'</span>)<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of negative values in `AirTime`: </span><span class="sc">{</span>negative_times<span class="sc">.</span>query(<span class="st">'AirTime &lt; 0'</span>)<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>display(negative_times.query(<span class="st">"ActualElapsedTime &lt; 0"</span>))</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>display(negative_times.query(<span class="st">"AirTime &lt; 0"</span>).sample(<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Number of negative values in `ActualElapsedTime`: 0
Number of negative values in `AirTime`: 27</code></pre>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
OriginState
</th>
<th data-quarto-table-cell-role="th">
DestState
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
<th data-quarto-table-cell-role="th">
ActualElapsedTime
</th>
<th data-quarto-table-cell-role="th">
AirTime
</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
OriginState
</th>
<th data-quarto-table-cell-role="th">
DestState
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
<th data-quarto-table-cell-role="th">
ActualElapsedTime
</th>
<th data-quarto-table-cell-role="th">
AirTime
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1123316
</td>
<td>
UT
</td>
<td>
MT
</td>
<td>
2004-05-16 22:40:00-06:00
</td>
<td>
2004-05-17 00:05:00-06:00
</td>
<td>
2004-05-16 22:35:00-06:00
</td>
<td>
2004-05-16 23:50:00-06:00
</td>
<td>
75
</td>
<td>
-60
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1179139
</td>
<td>
KY
</td>
<td>
OK
</td>
<td>
2004-12-19 09:45:00-05:00
</td>
<td>
2004-12-19 10:57:00-06:00
</td>
<td>
2004-12-19 10:15:00-05:00
</td>
<td>
2004-12-19 11:34:00-06:00
</td>
<td>
139
</td>
<td>
-594
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
1153657
</td>
<td>
GA
</td>
<td>
FL
</td>
<td>
2004-05-22 09:50:00-04:00
</td>
<td>
2004-05-22 11:18:00-05:00
</td>
<td>
2004-05-22 11:05:00-04:00
</td>
<td>
2004-05-22 12:18:00-05:00
</td>
<td>
73
</td>
<td>
-685
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1439783
</td>
<td>
TN
</td>
<td>
KY
</td>
<td>
2004-02-23 10:10:00-06:00
</td>
<td>
2004-02-23 11:15:00-05:00
</td>
<td>
2004-02-23 10:10:00-06:00
</td>
<td>
2004-02-23 11:11:00-05:00
</td>
<td>
61
</td>
<td>
-626
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
742574
</td>
<td>
NY
</td>
<td>
KY
</td>
<td>
2004-11-10 16:59:00-05:00
</td>
<td>
2004-11-10 19:00:00-05:00
</td>
<td>
2004-11-10 17:10:00-05:00
</td>
<td>
2004-11-10 19:03:00-05:00
</td>
<td>
113
</td>
<td>
-63
</td>
</tr>
</tbody>
</table>
</div>
<p>The filtered data shows that the number of negative values in these columns is extremely small (&lt;0.01% of the dataset). It is not clear from the sample data how are the values for <code>AirTime</code> calculated, since even with the deleted taxi variables the <code>AirTime</code> values are still not consistent with the difference between <code>WheelsOff</code> and <code>WheelsOn</code>. We decide therefore to drop the <code>AirTime</code> variable, as it is not clear how it is calculated and it is not consistent with the rest of the dataset.</p>
<p>The sample data for <code>ActualElapsedTime</code> confirms our hypothesis that the negative values are due to flights spanning across midnight and time zone differences. This leads to an even bigger realization: given the time variables do not contain time zone information, but are set in local times, both the <code>CRSElapsedTime</code> and <code>ActualElapsedTime</code> values do not represent the actual elapsed time for the flights. This is a major issue, since accurate time measurements for flight duraction might be very useful variable for feature engineeering and for our model. We will therefore also drop these features and replace them with an accurate calculation of the elapsed times, accounting for time zone differences.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Columns before drops: </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span><span class="st">'AirTime'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span><span class="st">'CRSElapsedTime'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span><span class="st">'ActualElapsedTime'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>sum_cols.remove(<span class="st">'AirTime'</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>sum_cols.remove(<span class="st">'CRSElapsedTime'</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>sum_cols.remove(<span class="st">'ActualElapsedTime'</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Columns after drops: </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Columns before drops: 45
Columns after drops: 42</code></pre>
</section>
<section id="feature-engineering-elapsed-time-calculation" class="level3">
<h3 data-anchor-id="feature-engineering-elapsed-time-calculation">Feature Engineering: Elapsed Time Calculation</h3>
<p>With time zones imputed for all time variables, we can accurately calculate the actual elapsed time for flights by converting the time variables to UTC and calculating the time difference between the <code>ArrTime_UTC</code> and <code>DepTime_UTC</code> variables. We will first convert the time variables to UTC.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> time_col <span class="kw">in</span> time_cols:</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    df[time_col <span class="op">+</span> <span class="st">'_UTC'</span>] <span class="op">=</span> pd.to_datetime(df[time_col], utc<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>display(df[time_cols <span class="op">+</span> [<span class="st">'OriginState'</span>, <span class="st">'DestState'</span>, <span class="st">'CRSDepTime_UTC'</span>, <span class="st">'DepTime_UTC'</span>, <span class="st">'CRSArrTime_UTC'</span>, <span class="st">'ArrTime_UTC'</span>]].head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime
</th>
<th data-quarto-table-cell-role="th">
DepTime
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime
</th>
<th data-quarto-table-cell-role="th">
ArrTime
</th>
<th data-quarto-table-cell-role="th">
OriginState
</th>
<th data-quarto-table-cell-role="th">
DestState
</th>
<th data-quarto-table-cell-role="th">
CRSDepTime_UTC
</th>
<th data-quarto-table-cell-role="th">
DepTime_UTC
</th>
<th data-quarto-table-cell-role="th">
CRSArrTime_UTC
</th>
<th data-quarto-table-cell-role="th">
ArrTime_UTC
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
1998-01-02 16:40:00-06:00
</td>
<td>
1998-01-02 16:59:00-06:00
</td>
<td>
1998-01-02 18:36:00-07:00
</td>
<td>
1998-01-02 18:59:00-07:00
</td>
<td>
MN
</td>
<td>
UT
</td>
<td>
1998-01-02 22:40:00+00:00
</td>
<td>
1998-01-02 22:59:00+00:00
</td>
<td>
1998-01-03 01:36:00+00:00
</td>
<td>
1998-01-03 01:59:00+00:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
2009-05-28 12:04:00-05:00
</td>
<td>
2009-05-28 12:02:00-05:00
</td>
<td>
2009-05-28 15:41:00-05:00
</td>
<td>
2009-05-28 15:41:00-05:00
</td>
<td>
WI
</td>
<td>
FL
</td>
<td>
2009-05-28 17:04:00+00:00
</td>
<td>
2009-05-28 17:02:00+00:00
</td>
<td>
2009-05-28 20:41:00+00:00
</td>
<td>
2009-05-28 20:41:00+00:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
2013-06-29 16:30:00-06:00
</td>
<td>
2013-06-29 16:44:00-06:00
</td>
<td>
2013-06-29 19:45:00-06:00
</td>
<td>
2013-06-29 19:42:00-06:00
</td>
<td>
CO
</td>
<td>
TX
</td>
<td>
2013-06-29 22:30:00+00:00
</td>
<td>
2013-06-29 22:44:00+00:00
</td>
<td>
2013-06-30 01:45:00+00:00
</td>
<td>
2013-06-30 01:42:00+00:00
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
2010-08-31 13:05:00-07:00
</td>
<td>
2010-08-31 13:05:00-07:00
</td>
<td>
2010-08-31 20:35:00-05:00
</td>
<td>
2010-08-31 20:15:00-05:00
</td>
<td>
CA
</td>
<td>
MI
</td>
<td>
2010-08-31 20:05:00+00:00
</td>
<td>
2010-08-31 20:05:00+00:00
</td>
<td>
2010-09-01 01:35:00+00:00
</td>
<td>
2010-09-01 01:15:00+00:00
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
2006-01-15 18:20:00-05:00
</td>
<td>
2006-01-14 19:11:00-05:00
</td>
<td>
2006-01-15 20:26:00-05:00
</td>
<td>
2006-01-15 20:58:00-05:00
</td>
<td>
NJ
</td>
<td>
NC
</td>
<td>
2006-01-15 23:20:00+00:00
</td>
<td>
2006-01-15 00:11:00+00:00
</td>
<td>
2006-01-16 01:26:00+00:00
</td>
<td>
2006-01-16 01:58:00+00:00
</td>
</tr>
</tbody>
</table>
</div>
<p>Now with the time variables in UTC, we can accurately calculate the actual elapsed time for the flights. We will recreate the <code>CRSElapsedTime</code> and <code>ActualElapsedTime</code> with the difference between the <code>ArrTime_UTC</code> and <code>DepTime_UTC</code> variables.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'CRSElapsedTime'</span>] <span class="op">=</span> ((df[<span class="st">'CRSArrTime_UTC'</span>] <span class="op">-</span> df[<span class="st">'CRSDepTime_UTC'</span>]).dt.total_seconds() <span class="op">/</span> <span class="dv">60</span>).astype(<span class="st">'int'</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'ActualElapsedTime'</span>] <span class="op">=</span> ((df[<span class="st">'ArrTime_UTC'</span>] <span class="op">-</span> df[<span class="st">'DepTime_UTC'</span>]).dt.total_seconds() <span class="op">/</span> <span class="dv">60</span>).astype(<span class="st">'int'</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>sum_cols.append(<span class="st">'CRSElapsedTime'</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>sum_cols.append(<span class="st">'ActualElapsedTime'</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>display(df[sum_cols].head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">
</th>
<th data-quarto-table-cell-role="th">
Distance
</th>
<th data-quarto-table-cell-role="th">
DistanceGroup
</th>
<th data-quarto-table-cell-role="th">
CRSElapsedTime
</th>
<th data-quarto-table-cell-role="th">
ActualElapsedTime
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">
0
</td>
<td>
991
</td>
<td>
4
</td>
<td>
176
</td>
<td>
180
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
1
</td>
<td>
1066
</td>
<td>
5
</td>
<td>
217
</td>
<td>
219
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
2
</td>
<td>
773
</td>
<td>
4
</td>
<td>
195
</td>
<td>
178
</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">
3
</td>
<td>
1979
</td>
<td>
8
</td>
<td>
330
</td>
<td>
310
</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">
4
</td>
<td>
529
</td>
<td>
3
</td>
<td>
126
</td>
<td>
1547
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="value-counts-updated" class="level3">
<h3 data-anchor-id="value-counts-updated">Value Counts (updated)</h3>
<p>Now that we have cleaned the flight summary variables and recalculated our elapsed time variables, we can now analyze the distribution of these variables. Below we plot the elapsed time variables.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, gridspec_kw<span class="op">=</span>{<span class="st">"height_ratios"</span>: (<span class="fl">.2</span>, <span class="fl">.8</span>)}, figsize<span class="op">=</span>figsize)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>axs <span class="op">=</span> axs.ravel()</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">'CRSElapsedTime'</span>, <span class="st">'ActualElapsedTime'</span>]):</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    sns.boxplot(x<span class="op">=</span>df[col], ax<span class="op">=</span>axs[i]).set_xlabel(<span class="st">''</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    sns.histplot(df[col], ax<span class="op">=</span>axs[i<span class="op">+</span><span class="dv">2</span>])</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>x_range <span class="op">=</span> df[[<span class="st">'CRSElapsedTime'</span>, <span class="st">'ActualElapsedTime'</span>]].values.flatten()</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>x_min, x_max <span class="op">=</span> x_range.<span class="bu">min</span>(), x_range.<span class="bu">max</span>()</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axs:</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(x_min <span class="op">-</span> <span class="dv">100</span>, x_max <span class="op">+</span> <span class="dv">100</span>)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="../assets/projects/04-univariate_analysis_2_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
<p>The distributions for the <code>CRSElapsedTime</code> and <code>ActualElapsedTime</code> variables are right skewed, with the majority of flights lasting less than</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 data-anchor-id="conclusion">Conclusion</h2>
<section id="takeaways" class="level3">
<h3 data-anchor-id="takeaways">Takeaways</h3>
</section>
<section id="exporting-dataset-and-variables" class="level3">
<h3 data-anchor-id="exporting-dataset-and-variables">Exporting Dataset and Variables</h3>
<div class="sourceCode" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df.to_parquet(<span class="st">'./data/interim/04-airline_2m.parquet'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>variables <span class="op">=</span> {name: value <span class="cf">for</span> name, value <span class="kw">in</span> <span class="bu">locals</span>().items() <span class="cf">if</span> name.endswith(<span class="st">'_cols'</span>)}</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'./src/modules/variables_04.py'</span>, <span class="st">'w'</span>) <span class="im">as</span> f:</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, value <span class="kw">in</span> variables.items():</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>        f.write(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>value<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>


</section>
</section>

 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
 <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2024 Marco-Andrés Camilo-Pietri</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>